### ISSUE TITLE
wcal help command mistake

### ISSUE THREAD

**Issue by ewiggin** [reimertz/wcal#2]
Hello!
I found one minor bug on `wcal help` command output.

This command `wcal <int:month> <int:year>     show wcal` not works. 
The correct command is `wcal list <int:month> <int:year>` works fine.

Regards,

**Comment by reimertz** [comment]
thanks homebrero, fixed and published in v0.0.3

**Comment by reimertz** [comment]
fuck, is misread what you said and instead introduced a bug. DERP!

**Comment by reimertz** [comment]
@ewiggin  wcal should now work as help suggests.

**Comment by reimertz** [comment]
actually not working. fuck it, I am going to write some tests now.

**Comment by ewiggin** [comment]
the issue are closed and fixed? I don't know about status of this 😅
